{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 4",
      "release_date": "2011-05-05T00:00:00Z",
      "advisory": "RHSA-2011:0491",
      "package": "python-0:2.3.4-14.10.el4",
      "cpe": "cpe:/o:redhat:enterprise_linux:4"
    },
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "release_date": "2011-05-05T00:00:00Z",
      "advisory": "RHSA-2011:0492",
      "package": "python-0:2.4.3-44.el5",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "release_date": "2011-05-19T00:00:00Z",
      "advisory": "RHSA-2011:0554",
      "package": "python-0:2.6.6-20.el6",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "release_date": "2011-05-19T00:00:00Z",
      "advisory": "RHSA-2011:0554",
      "package": "python-docs-0:2.6.6-2.el6",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    }
  ],
  "package_state": null,
  "threat_severity": "Moderate",
  "public_date": "2011-03-24T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)",
    "id": "690560",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560"
  },
  "cvss": {
    "cvss_base_score": "6.4",
    "cvss_scoring_vector": "AV:N/AC:L/Au:N/C:P/I:N/A:P",
    "status": "verified"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2011-1521",
  "document_distribution": "",
  "details": [
    "The urllib and urllib2 modules in Python 2.x before 2.7.2 and 3.x before 3.2.1 process Location headers that specify redirection to file: URLs, which makes it easier for remote attackers to obtain sensitive information or cause a denial of service (resource consumption) via a crafted URL, as demonstrated by the file:///etc/passwd and file:///dev/zero URLs."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2011-1521\nhttps://nvd.nist.gov/vuln/detail/CVE-2011-1521"
  ]
}