{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 3",
      "release_date": "2005-02-10T00:00:00Z",
      "advisory": "RHSA-2005:104",
      "package": "mod_python-0:3.0.3-5.ent",
      "cpe": "cpe:/o:redhat:enterprise_linux:3"
    },
    {
      "product_name": "Red Hat Enterprise Linux 4",
      "release_date": "2005-02-15T00:00:00Z",
      "advisory": "RHSA-2005:100",
      "package": "mod_python-0:3.1.3-5.1",
      "cpe": "cpe:/o:redhat:enterprise_linux:4"
    }
  ],
  "package_state": null,
  "threat_severity": "Moderate",
  "public_date": "2005-02-10T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2005-0088 security flaw",
    "id": "1617450",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1617450"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2005-0088",
  "document_distribution": "",
  "details": [
    "The publisher handler for mod_python 2.7.8 and earlier allows remote attackers to obtain access to restricted objects via a crafted URL."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2005-0088\nhttps://nvd.nist.gov/vuln/detail/CVE-2005-0088"
  ]
}