{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 6 Extended Lifecycle Support",
      "release_date": "2023-06-08T00:00:00Z",
      "advisory": "RHSA-2023:3550",
      "package": "python-0:2.6.6-69.el6_10",
      "cpe": "cpe:/o:redhat:rhel_els:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2023-06-09T00:00:00Z",
      "advisory": "RHSA-2023:3555",
      "package": "python-0:2.7.5-93.el7_9",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2023-06-09T00:00:00Z",
      "advisory": "RHSA-2023:3556",
      "package": "python3-0:3.6.8-19.el7_9",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-06-14T00:00:00Z",
      "advisory": "RHSA-2023:3594",
      "package": "python3.11-0:3.11.2-2.el8_8.1",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-06-14T00:00:00Z",
      "advisory": "RHSA-2023:3591",
      "package": "python3-0:3.6.8-51.el8_8.1",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "release_date": "2023-06-14T00:00:00Z",
      "advisory": "RHSA-2023:3585",
      "package": "python3.11-0:3.11.2-2.el9_2.1",
      "cpe": "cpe:/a:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "release_date": "2023-06-14T00:00:00Z",
      "advisory": "RHSA-2023:3595",
      "package": "python3.9-0:3.9.16-1.el9_2.1",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "gimp:flatpak/python2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "inkscape:flatpak/python2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python27:2.7/python2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python36:3.6/python36",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python38:3.8/python38",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python39:3.9/python39",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-python38-python",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Virtualization 4",
      "fix_state": "Affected",
      "package_name": "redhat-virtualization-host",
      "cpe": "cpe:/:redhat:enterprise_linux:::hypervisor"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2023-02-17T00:00:00Z",
  "bugzilla": {
    "description": "urllib.parse url blocklisting bypass",
    "id": "2173917",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2173917"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-24329",
  "document_distribution": "",
  "details": [
    "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
    "A flaw was found in the Python package. An issue in the urllib.parse component could allow attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.This may lead to compromised Integrity."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-24329\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-24329\nhttps://pointernull.com/security/python-url-parse-problem.html"
  ]
}