{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "ansible-lint",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "ansible-navigator",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "python3x-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "python-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-02-23T11:32:00Z",
  "bugzilla": {
    "description": "Denial of service by forcing null assertions with specially crafted input",
    "id": "2175704",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2175704"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-400",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-26303",
  "document_distribution": "",
  "details": [
    "Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.",
    "A denial of service vulnerability exists in markdown-it-py.An attacker could craft a payload with null assertations as input resulting in a crash and availability of the component"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-26303\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-26303"
  ]
}