{
  "affected_release": null,
  "package_state": null,
  "threat_severity": "",
  "public_date": "2002-08-01T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2002-1119 security flaw",
    "id": "1616838",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1616838"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2002-1119",
  "document_distribution": "",
  "details": [
    "os._execvpe from os.py in Python 2.2.1 and earlier creates temporary files with predictable names, which could allow local users to execute arbitrary code via a symlink attack."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2002-1119\nhttps://nvd.nist.gov/vuln/detail/CVE-2002-1119"
  ]
}