{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python-requests",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 3",
      "fix_state": "Will not fix",
      "package_name": "python-requests",
      "cpe": "cpe:/a:redhat:openstack:3"
    },
    {
      "product_name": "Red Hat OpenStack Platform 4",
      "fix_state": "Affected",
      "package_name": "python-requests",
      "cpe": "cpe:/a:redhat:openstack:4"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2013-12-25T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2014-1829 python-requests: redirect can expose netrc password",
    "id": "1046626",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1046626"
  },
  "cvss": {
    "cvss_base_score": "2.6",
    "cvss_scoring_vector": "AV:N/AC:H/Au:N/C:P/I:N/A:N",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-285-\u003eCWE-201",
  "statement": "This issue did not affect the versions of python-requests as shipped with Red Hat Enterprise Linux 7 as they included a fix for this issue at GA.\nRed Hat Product Security has rated this issue as having Low security impact. This issue is not currently planned to be addressed in future updates. For additional information, refer to the Issue Severity Classification: https://access.redhat.com/security/updates/classification/.",
  "acknowledgement": "",
  "name": "CVE-2014-1829",
  "document_distribution": "",
  "details": [
    "Requests (aka python-requests) before 2.3.0 allows remote servers to obtain a netrc password by reading the Authorization header in a redirected request."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2014-1829\nhttps://nvd.nist.gov/vuln/detail/CVE-2014-1829"
  ]
}