{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "python-gitpython",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Affected",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Affected",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Affected",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.0",
      "fix_state": "Affected",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:17.0"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Affected",
      "package_name": "python-gitpython",
      "cpe": "cpe:/a:redhat:satellite:6"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2022-12-05T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2022-24439 GitPython: improper user input validation leads into a RCE",
    "id": "2151583",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2151583"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "9.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-94",
  "statement": "Across all supported releases of Red Hat OpenStack Platform the usage of a compromised GitPython API (clone_from()) is quite limited. The only people capable of exploiting this vulnerability are system administrators. For this reason, the impact has been downgraded to medium.\nThe impact to Red Hat OpenStack Platform 17 is rated Low as the compromised function is not in use.",
  "acknowledgement": "Upstream acknowledges Sam Wheating as the original reporter.",
  "name": "CVE-2022-24439",
  "document_distribution": "",
  "details": [
    "All versions of package gitpython are vulnerable to Remote Code Execution (RCE) due to improper user input validation, which makes it possible to inject a maliciously crafted remote URL into the clone command. Exploiting this vulnerability is possible because the library makes external calls to git without sufficient sanitization of input arguments.",
    "A remote code execution vulnerability exists in Git-python. By injecting a malicious URL into the clone command, an attacker can exploit this vulnerability as the library makes external calls to git without any input sanitization. This issue leads to complete system compromise."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-24439\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-24439\nhttps://security.snyk.io/vuln/SNYK-PYTHON-GITPYTHON-3113858"
  ]
}